#include "nrf700x/osal/os_if/inc/osal_api.h"
#include "nrf700x/osal/os_if/inc/osal_ops.h"
#include "nrf700x/osal/os_if/inc/osal_structs.h"

#include "nrf700x/osal/fw_if/umac_if/inc/fmac_ap.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_api.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_bb.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_cmd.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_event.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_peer.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_rx.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_structs.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_tx.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_util.h"
#include "nrf700x/osal/fw_if/umac_if/inc/fmac_vif.h"
