#include "nrf700x/osal/fw_if/umac_if/inc/fmac_structs_common.h"
#include "nrf700x/osal/fw_if/umac_if/inc/default/fmac_api.h"
#include "nrf700x/osal/os_if/inc/osal_ops.h"
#include "nrf700x/osal/bus_if/bal/inc/bal_ops.h"
#include "nrf700x/osal/bus_if/bal/inc/bal_structs.h"
#include "nrf700x/osal/hw_if/hal/inc/hal_structs.h"
