[unstable]
# build-std = ["core"]
#build-std-features = ["panic_immediate_abort"]

[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip nRF5340_xxAA --allow-erase-all"

[build]
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "info,nrf7002_example=trace"
DEFMT_RTT_BUFFER_SIZE = "8192"